#TestError Exception.
class TestError(Exception):
    pass
